server { 
	listen 80a;
}
#de momento lo aceptamos como válido pero creo que no debería serlo
#comprobar validez de TODOS los valores

server { listen 8080; 
}
#sale error, debería ser válido?


server { 
	listen 8080; location / {root /tmp; }
}
#creo que es el mismo problema de antes, analizamos por línea? deberíamos analizar por token?

#en el archivo de configuracion puede haber varios servers escuchando en el mismo puerto?
#gemini dice que solo si vamos a implementar virtual hosts


#revisar cgi, se descarga cuando la extensión no está en la lista, raro
#si es un archivo y no es un cgi, leer como archivo estático html, sacar del archivo 