# ==============================================================================
# Servidor 1: Servidor principal (Puerto 8080)
# ==============================================================================
server { listen 8085; server_name localhost; }

# ==============================================================================
# Servidor 2: Servidor secundario (Puerto 8081)
# ==============================================================================
server {
    listen 8081;
    server_name example.com;

    host 0.0.0.0;

    root ./www/example;
    index default.html;
    client_max_body_size 58530000000000000000001210; # 1 MB

    location / { allow_methods GET; autoindex on; }

    # Redirección interna
    location /old_path {
        return 301 /;
    }
}